#!/usr/bin/env ruby

# This file contains code to massage docs files from a repository to fit on the web

require_relative 'src/documentation_formatter'

docs_dir = ARGV[0]
ns = ARGV[1]
repo_name = ARGV[2]
repo_tag = ARGV[3]
docs_menu_file = ARGV[4]
shared_docs_menus_file = ARGV[5]

formatter = DocumentationFormatter.new()

formatter.update_docs_content(docs_dir, ns, repo_name, repo_tag)
formatter.add_to_docs_menus(docs_menu_file, shared_docs_menus_file, ns)
