#!/usr/bin/env ruby

# This file contains code to massage docs files from a repository to fit on the web

require 'yaml'

def add_name_space_to_front_matter_in_docs(docs_dir, ns, repo_name)
  Dir.glob(File.join(docs_dir, '*.md')).each do | file|
    update_front_matter_data(file, ns, repo_name)
  end
end

def update_front_matter_data(file, ns, repo_name)
  doc = IO.read(file)
  data = YAML.load(doc)
  data['page_id'] = ns + data['page_id']
  data['layout'] = 'page-docs'
  data['repo_name'] = repo_name
  data['ns'] = ns

  start_of_front_matter = doc.index('---')
  end_of_front_matter = doc.index('---', start_of_front_matter + 3)
  result = data.to_yaml + doc[end_of_front_matter..-1]

  IO.write(file, result)
end

def add_name_space_to_node_list(nodes, ns)
  nodes.each do |node|
    if node.key? 'page_id'
      node['page_id'] = ns + node['page_id']
    end

    if node.key? 'subs'
      add_name_space_to_node_list(node['subs'], ns)
    end
  end
end

def add_to_docs_menus(docs_menu_file, shared_docs_menus_file, ns)
  repo_menus = YAML.load_file(docs_menu_file)
  add_name_space_to_node_list(repo_menus, ns)

  if File.file? shared_docs_menus_file
    shared_menus = YAML.load_file(shared_docs_menus_file)
  else
    shared_menus = {}
  end

  shared_menus[ns] = repo_menus

  IO.write(shared_docs_menus_file, shared_menus.to_yaml)
end


docs_dir = ARGV[0]
menu_file = ARGV[1]
ns = ARGV[2]
repo_name = ARGV[3]
docs_menu_file = ARGV[4]
shared_docs_menus_file = ARGV[5]

add_name_space_to_front_matter_in_docs(docs_dir, ns, repo_name)
add_to_docs_menus(docs_menu_file, shared_docs_menus_file, ns)

