#!/usr/bin/env ruby

# This file contains code to massage docs files from a repository to fit on the web

require_relative 'src/documentation_formatter'

docs_dir = ARGV[0]
ns = ARGV[1]
repo_name = ARGV[2]
repo_tag = ARGV[3]
repo_root_url = ARGV[4]
docs_menu_file = ARGV[5]
shared_docs_menus_file = ARGV[6]
docs_tag_list_file = ARGV[7]
directives = ARGV[8]

formatter = DocumentationFormatter.new()

formatter.update_docs_content(docs_dir, ns, repo_name, repo_tag, repo_root_url, directives)
formatter.add_to_docs_menus(docs_menu_file, shared_docs_menus_file, ns)
formatter.add_to_docs_tag_list_file(docs_tag_list_file, repo_name, repo_tag)
